# /etc/skel/.bashrc
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Disable creation of the ~/.lesshst file
export LESSHISTFILE=-

# Python shell initilization location
export PYTHONSTARTUP=~/.config/python/pythonrc

# Change location of .Xauthority file
export XAUTHORITY=~/.config/x/Xauthority

# Change location of .bash_history file
export HISTFILE=~/.local/history/bash_history

# Change location of global git config
export GIT_CONFIG_GLOBAL=~/.config/git/gitconfig

# Set the base directory for XDG specification
export XDG_CONFIG_HOME=~/.config

# Add rust packages to PATH
source ~/.cargo/env

# Get any sensitive information configured on the local system (stuff that you shouldn't store in VC
source ~/.config/bash/personal.env

alias resetaws="rm -f ~/.config/bash/aws-session.env; source ~/.config/bash/aws.env" # Removes an aws session and returns to default aws credentials
alias sx="startx ~/.config/x/xinitrc" # Start X with the custom xinitrc 
alias feature="t --task-dir ./.tasks/features/" # Create a feature task in the current directory
alias bug="t --task-dir ./.tasks/bugs/" # Create a bug task in the current directory
alias tf="terraform" # Just a shorter form of typing terraform
alias get-aws-creds="~/.scripts/aws/get-aws-creds" # Shortcut for get-aws-creds command
aws-decode() { # Decodes an encoded authorization message from AWS
  aws sts decode-authorization-message --encoded-message $1
}

list_tasks() { # Helper function for tlist alias
  _features=$(t --task-dir ./.tasks/features --list tasks)
  _bugs=$(t --task-dir ./.tasks/bugs --list tasks)
  readarray -t features <<<"$_features"
  readarray -t bugs <<<"$_bugs"
  for feature in "${features[@]}"
  do
    echo "[FEATURE] $feature"
  done

  for bug in "${bugs[@]}"
  do
    echo "[BUG] $bug"
  done
}
alias tlist='list_tasks' # Lists the tasks in a repo

# Get AWS credentials if this system has them
if [[ -e ~/.config/bash/aws.env ]]; then
  source ~/.config/bash/aws.env
fi


