# /etc/skel/.bashrc
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Disable creation of the ~/.lesshst file
export LESSHISTFILE=-

# Python shell initilization location
export PYTHONSTARTUP=~/.config/python/pythonrc

# Change location of .Xauthority file
export XAUTHORITY=~/.config/x/Xauthority

# Change location of .bash_history file
export HISTFILE=~/.local/history/bash_history

# Change location of global git config
export GIT_CONFIG_GLOBAL=~/.config/git/gitconfig

# Set the base directory for XDG specification
export XDG_CONFIG_HOME=~/.config

# Add rust packages to PATH
source ~/.cargo/env

# Get any sensitive information configured on the local system (stuff that you shouldn't store in VC
source ~/.config/bash/personal.env

alias cdg="cd ~/code" # Shortcut to go to code directory
alias cdp="cd ~/code/personal" # Shortcut to go to personal code directory
alias cdps="cd ~/code/personal/scripts" # Shortcut to go to personal scripts directory
alias cdpc="cd ~/code/personal/configs" # Shortcut to go to personal configs directory
alias cdr="cd ~/code/rosales" # Shortcut to go to rosales code directory
alias resetaws="rm -f ~/.config/bash/aws-session.env; source ~/.config/bash/aws.env" # Removes an aws session and returns to default aws credentials
alias sx="startx ~/.config/x/xinitrc" # Start X with the custom xinitrc 
alias feature="t --task-dir ./.tasks/features/" # Create a feature task in the current directory
alias bug="t --task-dir ./.tasks/bugs/" # Create a bug task in the current directory
alias tf="terraform" # Just a shorter form of typing terraform
alias get-aws-creds="source ~/.scripts/aws/get-aws-creds" # Shortcut for get-aws-creds command

list_tasks() { # Helper function for tlist alias
  _features=$(t --task-dir ./.tasks/features --list tasks)
  _bugs=$(t --task-dir ./.tasks/bugs --list tasks)
  readarray -t features <<<"$_features"
  readarray -t bugs <<<"$_bugs"
  for feature in "${features[@]}"
  do
    echo "[FEATURE] $feature"
  done

  for bug in "${bugs[@]}"
  do
    echo "[BUG] $bug"
  done
}
alias tlist='list_tasks' # Lists the tasks in a repo

# Get AWS credentials if this system has them.
# These are default credentials. If the IAM account you want to access requires MFA, you'll have to 
# use get-aws-creds to get MFA-compatible creds.
if [[ -e ~/.config/bash/aws.env ]]; then
  source ~/.config/bash/aws.env
fi
