# /etc/skel/.bashrc
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Disable creation of the ~/.lesshst file
export LESSHISTFILE=-

# Python shell initilization location
export PYTHONSTARTUP=~/.config/python/pythonrc

# Change location of .Xauthority file
export XAUTHORITY=~/.config/x/Xauthority

# Change location of .bash_history file
export HISTFILE=~/.local/history/bash_history

# Change location of global git config
export GIT_CONFIG_GLOBAL=~/.config/git/gitconfig

# Set the base directory for XDG specification
export XDG_CONFIG_HOME=~/.config

# Add rust packages to PATH
source ~/.cargo/env

alias sx="startx ~/.config/x/xinitrc" # Start X with the custom xinitrc 
alias feature="t --task-dir ./.tasks/features/"
alias bug="t --task-dir ./.tasks/bugs/"
alias tf="terraform"

list_tasks() {
  _features=$(t --task-dir ./.tasks/features --list tasks)
  _bugs=$(t --task-dir ./.tasks/bugs --list tasks)
  readarray -t features <<<"$_features"
  readarray -t bugs <<<"$_bugs"
  for feature in "${features[@]}"
  do
    echo "[FEATURE] $feature"
  done

  for bug in "${bugs[@]}"
  do
    echo "[BUG] $bug"
  done
}
alias tlist='list_tasks'

# Get AWS credentials if this system has them
if [[ -e ~/.config/bash/aws ]]; then
  source ~/.config/bash/aws
fi
